### ISSUE TITLE
🌎 Add Indonesian Language

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#47]
Add Indonesian as a supported language.

I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md).

Please go through the checklist so that you won’t miss anything!

**Comment by seryafarma** [comment]
Hey, while translating I notice this checkmark:
https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md

> Removed duplicates and noted them in the Pull Request.

What does this mean?
is it duplicate in the word?

For example these two words are having the same Indonesian translation:
kongres | Congress
kongres | congressional

If so, can I easily spot them later on? I found quite a few since in Indonesian the same word can have more than one meaning.

**Comment by jayehernandez** [comment]
Hey @seryafarma, Apologies for the unclear instructions, words with the same translation are fine to include, no need to remove these.

What I was referring to for the duplicates is if for example the translation is:
`Congress => Congress`

which makes no sense to include if ever. Hope this helps in clarifying!

**Comment by seryafarma** [comment]
[duplicates.txt](https://github.com/jayehernandez/letra-extension/files/4673799/duplicates.txt)

These are the duplicates in Indonesian language, I have removed the section from json file.
Might be good to show people how to best do this from the google sheet.

**Comment by jayehernandez** [comment]
Thanks for the suggestion! I’ll be sure to note that in the documentation. Also saw your PR, reviewing it in a bit. 😁

**Comment by arcestia** [comment]
Can i update more words to the list?

**Comment by jayehernandez** [comment]
@arcestia what do you mean by this, would you like to edit the translations or add more words? Currently, we don't allow adding of words outside of the 3000 words. Let me know!

**Comment by arcestia** [comment]
Just want to add a more commonly used word in Indonesian.
