### ISSUE TITLE
Unable to locate Voice attribute for Yoruba Language 

### ISSUE THREAD

**Issue by profread** [jayehernandez/letra-extension#490]
Unable to find the voice attribute for Yoruba language.
can it be added.
Will like to know how to create one.
Thanks

**Comment by Kvaibhav01** [comment]
Hey! What do you mean by "voice attribute"? Are you talking about the [supported voices](https://github.com/jayehernandez/letra-extension/blob/master/docs/supported_voices.md)?

**Comment by profread** [comment]
Yes, Supported voices

**Comment by Kvaibhav01** [comment]
@profread we are using the [ResponsiveVoice API](https://responsivevoice.org/text-to-speech-languages/) for the voice feature and unfortunately, the Yoruba language isn't supported as you can see in [this file list](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md).

**Comment by profread** [comment]
Okay thanks but I can still work on the word translate for this language?

**Comment by Kvaibhav01** [comment]
@jayehernandez need your comment.

**Comment by jayehernandez** [comment]
Thanks for tagging @Kvaibhav01, since it's the voice for Yoruba isn't supported yet, it would be harder for those who want to learn the language to know how to pronounce the words without a guide.

Wouldn't want to waste your effort in translating @profread! If it's already supported, I'd be happy to let you translate.

Closing this issue for now, feel free to reopen.

**Comment by profread** [comment]
Okay, will work on other languages then. Thanks
