### ISSUE TITLE
🐛 Long words overflow to end of screen

### ISSUE THREAD

**Issue by jayehernandez** [jayehernandez/letra-extension#95]
I didn't really test this out for very long words. Probably not a problem with other languages but it's a good thing the language I'm learning now is German 💁🏻‍♀️

<img width="1669" alt="Screen Shot 2020-05-25 at 1 41 23 PM" src="https://user-images.githubusercontent.com/13959651/83126394-51f5d900-a10b-11ea-83dd-1d04ba168a31.png">

Best solution would probably be changing the font size depending on the word! Would prefer this over cutting off the word using `text-overflow`.

**Comment by tbarland77** [comment]
I see this one has been sitting for a bit. Mind if I work on it @jayehernandez? I also noticed that the audio button seems to move on top of the word if it's really long. Would that be considered a separate issue or would we expect that to no longer be an issue after this is resolved? I did see in the chrome dev tools if I take the font-size down to 7vw that it seems to fix the audio button placement as well.

**Comment by jayehernandez** [comment]
Sure, assigning you to this issue @tbarland77! I think the audio button should be fixed in this issue as well. Maybe we can add a condition to change the font-size if the word is beyond a certain length? I tried changing the font-size to 7vw but it's a bit small for shorter words. Let me know what you think.

**Comment by tbarland77** [comment]
Thanks! Yeah, I was thinking maybe we could also let the word go to a second line, but I'm not sure if that would fix the audio button issue or not. Using a computed property to change the font-size based on the length of the word is probably the way to go. Unless maybe there is a way to dynamically change font-size with scss? I might look into that to see if it's possible. That makes sense since I believe vw goes off of the width of the viewport.

Anyway, I'll see if pure scss could be used for this and if not I'll just see about using a computed property for the font-size based on the word length.

**Comment by jayehernandez** [comment]
Closed by #129
